HOMS-227 Change login and password to environment variables
latera/activiti-homs-docker pull request #6
Opened 2018-10-04 15:41 UTC by mxsmirnoff

2018-10-04 15:49 UTC, sugarfree1 requested changes

2018-10-04 15:49 UTC, sugarfree1 commented on populate.sh
> +	echo $ACTIVITI_LOGIN
We don't need ```echo``` here.

2018-10-08 07:33 UTC, mxsmirnoff commented
Updated

2018-10-09 08:28 UTC, sugarfree1 approved these changes

2018-10-09 15:47 UTC, merged